name = "Applications Setup"

[[data]]
name = "Communication Apps"

[[data.entries]]
name = "Discord"
description = "Discord is a versatile communication platform for gamers and communities, offering voice, video, and text chat features."
script = "communication-apps/discord-setup.sh"
task_list = "I"

[[data]]
name = "Developer Tools"

[[data.entries]]
name = "Github Desktop"
description = "GitHub Desktop is a user-friendly application that simplifies the process of managing Git repositories and interacting with GitHub, providing a graphical interface for tasks like committing, branching, and syncing changes."
script = "developer-tools/githubdesktop.sh"
task_list = "I"

[[data.entries]]
name = "JetBrains Toolbox"
description = "JetBrains Toolbox is a collection of tools and an app that help developers work with JetBrains products."
script = "developer-tools/jetbrains-toolbox.sh"
task_list = "I"

[[data.entries]]
name = "Meld"
description = "Meld is a visual diff and merge tool that helps compare files, directories, and version-controlled projects."
script = "developer-tools/meld.sh"
task_list = "I FI"

[[data.entries]]
name = "Neovim"
description = "Neovim is a refactor, and sometimes redactor, in the tradition of Vim.\nIt is not a rewrite but a continuation and extension of Vim.\nThis command configures neovim from CTT's neovim configuration.\nhttps://github.com/ChrisTitusTech/neovim"
script = "developer-tools/neovim.sh"
task_list = "I FM"

[[data.entries]]
name = "Ngrok"
description = "Ngrok is a tool that creates secure, temporary tunnels to expose local servers to the internet for testing and development."
script = "developer-tools/ngrok.sh"
task_list = "I"

[[data.entries]]
name = "Sublime Text"
description = "Sublime Text is a fast, lightweight, and customizable text editor known for its simplicity, powerful features, and wide range of plugins for various programming languages."
script = "developer-tools/sublime.sh"
task_list = "I"

[[data.entries]]
name = "VS Code"
description = "Visual Studio Code (VS Code) is a lightweight, open-source code editor with built-in support for debugging, version control, and extensions for various programming languages and frameworks."
script = "developer-tools/vscode.sh"
task_list = "I"

[[data.entries]]
name = "VS Codium"
description = "VSCodium is a free, open-source version of Visual Studio Code (VS Code) that removes Microsoft-specific telemetry and branding."
script = "developer-tools/vscodium.sh"
task_list = "I"

[[data.entries]]
name = "Zed"
description = "Zed is a next-generation code editor written in rust, designed for high-performance collaboration with humans and AI."
script = "developer-tools/zed.sh"
task_list = "I"

[[data]]
name = "Office Suites"

[[data.entries]]
name = "FreeOffice"
script = "office-suites/freeoffice.sh"
task_list = "I"

[[data.entries]]
name = "LibreOffice"
script = "office-suites/libreoffice.sh"
task_list = "I"

[[data.entries]]
name = "OnlyOffice"
script = "office-suites/onlyoffice.sh"
task_list = "I"

[[data.entries]]
name = "WPS Office"
script = "office-suites/wpsoffice.sh"
task_list = "I"

[[data]]
name = "Web Browsers"

[[data.entries]]
name = "Brave"
description = "Brave is a free and open-source web browser developed by Brave Software, Inc. based on the Chromium web browser."
script = "browsers/brave.sh"
task_list = "I"

[[data.entries]]
name = "Lynx"
description = "Lynx is a highly configurable text-based web browser for use on cursor-addressable character cell terminals."
script = "browsers/lynx.sh"
task_list = "I"

[[data.entries]]
name = "Zen Browser"
description = "Zen Browser is a privacy-focused web browser designed for enhanced security and a seamless browsing experience."
script = "browsers/zen-browser.sh"
task_list = "I"

[[data.entries]]
name = "Thorium"
description = "Thorium is a Chromium-based browser focused on privacy and performance."
script = "browsers/thorium.sh"
task_list = "I"

[[data.entries]]
name = "Vivaldi"
description = "Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies."
script = "browsers/vivaldi.sh"
task_list = "I"

[[data.entries]]
name = "waterfox"
description = "Waterfox is the privacy-focused web browser engineered to give you speed, control, and peace of mind on the internet."
script = "browsers/waterfox.sh"
task_list = "FI"

[[data]]
name = "Fastfetch"
description = "Fastfetch is a neofetch-like tool for fetching system information and displaying it prettily. It is written mainly in C, with performance and customizability in mind. This command installs fastfetch and configures from CTT's mybash repository. https://github.com/ChrisTitusTech/mybash"
script = "fastfetch-setup.sh"
task_list = "I FM"

[[data]]
name = "Flatpak / Flathub"
description = "Flatpak is a universal application sandbox for Linux that uses isolated packages from Flathub to prevent conflicts and system alterations, while alleviating dependency concerns. This command installs Flatpak and adds the Flathub repository"
script = "setup-flatpak.sh"
task_list = "I"

[[data]]
name = "Grub Theme"
description = "Installs ChrisTitusTech's Top 5 Bootloader Themes script to allow for easy customization of GRUB."
script = "grub-theme.sh"
task_list = "PFM"

[[data]]
name = "Kitty"
description = "kitty is a free and open-source GPU-accelerated terminal emulator for Linux, macOS, and some BSD distributions, focused on performance and features. kitty is written in a mix of C and Python programming languages. This command installs and configures kitty."
script = "kitty-setup.sh"
task_list = "I FM"

[[data.preconditions]]
matches = false
data = "command_exists"
values = ["linutil"]

[[data.preconditions]]
matches = true
data = "command_exists"
values = ["linutil"]

[[data]]
name = "ZSH Prompt"
description = "The Z shell is a Unix shell that can be used as an interactive login shell and as a command interpreter for shell scripting. Zsh is an extended Bourne shell with many improvements, including some features of Bash, ksh, and tcsh. This command installs ZSH prompt and provides basic configuration."
script = "zsh-setup.sh"
task_list = "I FM"

[[data]]
name = "Rocm Install"
description = "This script installs ROCm (Radeon Open Compute) on supported AMD GPUs for high-performance computing and machine learning tasks."
script = "rocm-install.sh"
